### ISSUE TITLE
LaunchTemplate support for MNG broken with v14.0.0

### ISSUE THREAD

**Issue by philicious** [terraform-aws-modules/terraform-aws-eks#1211]
# I have issues

## I'm submitting a...

* [x] bug report

## What is the current behavior?

https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1129 that got released with `v14.0.0` breaks the LT-support for MNG that got added by me with #997 and 13.1 !

when using an LT, you cannot set instance-type on the MNG itself ! however this commit breaks the logic

https://github.com/terraform-aws-modules/terraform-aws-eks/commit/8978997bb1d5a769f03eac764d4da3caddfb9c76#diff-7a3fc6c7df17fda0c341e61255461bf1f149256a9ddf14d4a18ab6f020d08136

using v14.0.0, TF wrongly wants to add the instance_type to existing MNG with LT but then also fails while trying so. 

>InvalidRequestException: Cannot specify instance types in launch template and API request

## If this is a bug, how to reproduce? Please include a code sample if relevant.

try to create or run on existing MNG with LT

## What's the expected behavior?

no regression. behavior <14.0 is expected

## Environment details

* Affected module version: v14.0.0
* OS: macOS 11.0.1
* Terraform version: 0.14.5

## Any other relevant info

**Comment by psoares** [comment]
Can you try with my branch? See #1161

**Comment by philicious** [comment]
@psoares on a quick glance your PR looks more promising. 
I'll give it a shot tomorrow.

**Comment by philicious** [comment]
@psoares I can confirm that your branch / ( #1161 ) is not affected and properly treats the instance_type on the MNG in case a LT is set.

**Comment by dusansusic** [comment]
I tested this but it still wants to recreate my existing node groups with launch templates. Have you tested this? I will have more time during weekend.

**Comment by ado120** [comment]
I would like to add that I am also running into this issue, set a instance type in a LT as well as under node_groups and am getting the same error

**Comment by philicious** [comment]
@ado120 if I understand correctly: you set instance_type on both LT and the node_group block itself. 
So that is forbidden. You can only set in either. 

However, without this fix here, you still get an error if you only set in LT as the module wrongly adds a default value then in the node_group

**Comment by philicious** [comment]
@ado120 well, I set `instance_type` on the LT but pinned the module to `version  = "<14.0.0" ` but setting it only on the node_group should also work and w/o pinning according to 
>If you deploy a node group using a launch template, then you can specify zero or one Instance type under Launch template contents in a launch template or you can specify 0-20 instance types for Instance types on the Set compute and scaling configuration page in the console, or using other tools that use the Amazon EKS API

**Comment by pmargarc** [comment]
I just ran into the mentioned exception today. What should be the best solution to the problem?
I checked the module's docs and didn't find anything about `instance type` attribute in `layout_template` block for `aws_eks_node_group`.
:) thank you

**Comment by philicious** [comment]
@pmargarc set `instance_type` either in the LT or in the `node_groups { ..}` block. 
you also need to pin the module version `version = "<14.0.0"` in case you set `instance_type` in the LT

**Comment by pmargarc** [comment]
Solved!! It didn't have anything to do with that finally :)
Somehow `instance_type` was being defined in 2 files at the same time (launchtemplate.tf and node_groups.tf). That was generating the issue.

Btw, specifying ` version = "<14.0.0"` got me this error -> "Invalid kubernetes version <14.0.0" and had to switch to the original settings (`version = lookup(each.value, "version", null)`.

Thanks a lot 👍

**Comment by philicious** [comment]
fixed by #1138

**Comment by jai** [comment]
I'm still experiencing this issue in [17.1.0](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/v17.1.0)

**Comment by philicious** [comment]
@jai it should not happen anymore. 
- make sure you only set instance_type on either the Launchtemplate or the node_group, not both. 
- try updating module to a newer or latest 17.x 

If that doesn't help, maybe you can share your EKS code
