### ISSUE TITLE
Support target_group_arns for managed node groups

### ISSUE THREAD

**Issue by DmitriyStoyanov** [terraform-aws-modules/terraform-aws-eks#1539]
## Is your request related to a new offering from AWS?
This feature request opened in aws provider for node groups
https://github.com/aws/containers-roadmap/issues/709

but separate part can be added in module to support this feature

## Is your request related to a problem? Please describe.
For the moment, we used nginx ingress controller and worker groups attached to alb via property `target_group_arns`
(A list of Application LoadBalancer (ALB) target group ARNs to be associated to the autoscaling group)

When we added managed node groups we found that alb target group does not contain instances from managed node groups. So ingress cannot work on these instances.

## Describe the solution you'd like.

option as a `target_group_arns` for node_groups

## Describe alternatives you've considered.

Currently to mitigate this issue we created separate resource (thanks to https://github.com/aws/containers-roadmap/issues/709#issuecomment-608333853 ) :
```
resource "aws_autoscaling_attachment" "autoscaling_attachment" {
  for_each = {for name, value in module.eks.node_groups : name => lookup(lookup(lookup(value, "resources")[0], "autoscaling_groups")[0], "name")}
  autoscaling_group_name = each.value
  alb_target_group_arn   = aws_lb_target_group.alb.arn
}
```
So this part can be added in node_group submodule

**Comment by daroga0002** [comment]
why you cannot use normal service `Type=Loadbalancer`  or something like https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/nlb/ ?

**Comment by DmitriyStoyanov** [comment]
> why you cannot use normal service `Type=Loadbalancer` or something like https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/nlb/ ?

From my case, I had previously created LB for nginx ingress for whole cluster and it was attached to ALB group via `target_group_arns`. But when I started to add managed nodegroups, faced, that this balancer cannot be attached to these node groups because of unavailability of such parameter in node group submodule. So it is added as separate `aws_autoscaling_attachment`. If it will be added to submodule, it can be used as the same parameter directly during module description.

**Comment by daroga0002** [comment]
why you cannot use cloud provider?

**Comment by DmitriyStoyanov** [comment]
Because ALB already exist in separate terraform module, with management of Security groups, WAF, Certificates, etc... in separate module. 
And by the way, one of our cluster in China, so you cannot just recreate your LB, if you already pinned it with static IP's and applied ICP License for that stuff.

**Comment by jaimehrubiks** [comment]
@daroga0002 Many of us don't use service type "LoadBalancer" because we prefer to use terraform when creating infrastructure. That way we can manage security groups, dns, and so on in a much controlled way than when kubernetes creates it automatically.

That said I use this without trouble

# ELB_NAME
resource "aws_autoscaling_attachment" "node_groups--ELB_NAME" {
  for_each = module.eks.node_groups

  autoscaling_group_name = lookup(lookup(lookup(each.value, "resources")[0], "autoscaling_groups")[0], "name")
  elb                    = aws_elb.elb_ELB_NAME.id
}

**Comment by DmitriyStoyanov** [comment]
From my side I already solved this issue by creation of
```
resource "aws_autoscaling_attachment" "autoscaling_attachment" {
  for_each = {for name, value in module.eks.node_groups : name => lookup(lookup(lookup(value, "resources")[0], "autoscaling_groups")[0], "name")}
  autoscaling_group_name = each.value
  alb_target_group_arn   = aws_lb_target_group.alb.arn
}
```

And just created this issue, to possible add this ability in the module as we already have for asg groups.

Or possible if someone also will face with the same issue, the same approach can be used.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 18.0.0 :tada:

**Comment by mprzygrodzki** [comment]
@antonbabenko - marked as resolved, but I still don't understand the context how. I've same situation as @kkapoor1987 where mentioned before, we have deployed our own ALB and things related to it via TF - and now and in the near future there's no possibility to use mentioned AWS ALB Controller. I've also started to migrate our self managed workers to use managed worker groups directly from module in 18.7.2. So what's the final point for this topic ? Is there any possibility to pass **target_group_arn** somehow to managed node group ?

@kkapoor1987 - did you managed to pass that issue ? If so - would you be kind to show me how ?

**Comment by bryantbiggs** [comment]
@mprzygrodzki there aren't any options to pass `target_group_arn` anywhere - as far as I can tell, this is not supported in launch templates so I'm not sure how others were doing this previously (as mentioned above). The issue was closed due to stale activity, but I suspect because there was a reference of this issue in v18 somewhere, the release automation commented here (a bit of a fluke if you will). 

That said, there isn't anything for us to do here in this module. Users can take the outputs and grab the autoscaling groups created and create the ALB attachments outside of this module

**Comment by mprzygrodzki** [comment]
@bryantbiggs - ok, thanks for clarification.

**Comment by kkapoor1987** [comment]
@mprzygrodzki I was able to make it work by following https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1539#issuecomment-923041249

Its not perfect but if you have ASG info then you can `aws_autoscaling_attachment`. It seems like module was creating attachments for self managed worker groups but not for managed worker group nodes. I think we are also moving away from `aws_autoscaling_attachment` and adopting alb controller to that as its much cleaner approach. Please, let me know if you still need help I can walk you through the `aws_autoscaling_attachment` hack we have in place

**Comment by mconigliaro** [comment]
It got easier in `18.x`:

```
resource "aws_autoscaling_attachment" "this" {
  for_each               = toset(module.eks.eks_managed_node_groups["generic"].node_group_autoscaling_group_names)
  autoscaling_group_name = each.value
  alb_target_group_arn   = aws_lb_target_group.lb.arn
}
```
