### ISSUE TITLE
KMS Policy error in 19.0 when using iam role for aws provider

### ISSUE THREAD

**Issue by pdeva** [terraform-aws-modules/terraform-aws-eks#2327]
## Description

Trying to create a new eks cluster with module version 19.0 runs into a `MalformedPolicyDocumentException` error while creating the kms key internally.

- [ x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 19.0.3

- Terraform version: 1.3.6

- Provider version(s): aws provider: 4.45.0

## Reproduction Code [Required]

This simple code is enough to reproduce the error:

```hcl
module "eks_cluster" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "~> 19.0"
  vpc_id          = module.vpc.vpc_id
  cluster_name    = "k1"
  cluster_version = "1.24"
  subnet_ids      = module.vpc.private_subnet_ids

  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = false

}
```

AWS provider configuration:

```hcl
provider "aws" {
  region              = "us-east-1"
  allowed_account_ids = ["172512501118"]
  assume_role {
    role_arn = "arn:aws:iam::172512501118:role/terraform"
  }
}
```

the iam `role` above has `AdministrativeAccess` policy attached.

## Expected behavior

Cluster should be created without errors.

## Actual behavior

Getting this error:

```
Error: error creating KMS Key: MalformedPolicyDocumentException: The new key policy will not allow you to update the key policy in the future.
with module.us_east_1.module.eks_cluster.module.kms.aws_kms_key.this[0]
on .terraform/modules/us_east_1.eks_cluster.kms/main.tf line 8, in resource "aws_kms_key" "this":
resource "aws_kms_key" "this" {
```

### Terminal Output Screenshot(s)
<img width="1143" alt="Screenshot 2022-12-07 at 6 57 48 AM" src="https://user-images.githubusercontent.com/3190176/206212853-8b88384f-9b5c-43bd-b709-c8ed8555daa4.png">

**Comment by bryantbiggs** [comment]
please check open issues first per the template: duplicate of #2321 and #2325

**Comment by pdeva** [comment]
hi @bryantbiggs. the reason to create this issue was that those 2 issues seem to relate to upgrading from older version of module to newer version. And there the OP wants to turn off encryption completely.  

I think the right solution would have the cluster be created with encryption and without any errors, which is what I am trying to do here.

**Comment by bryantbiggs** [comment]
they are related and will all be solved by #2318

**Comment by pdeva** [comment]
@bryantbiggs so this issue is still present in `19.0.4` which has  #2318.

Here is the exact code to reproduce:

```hcl
module "eks_cluster" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "19.0.4"
  vpc_id          = module.vpc.vpc_id
  cluster_name    = "k1"
  cluster_version = "1.24"
  subnet_ids      = module.vpc.private_subnet_ids

  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = false

}
```

And here is the error:
<img width="1152" alt="Screenshot 2022-12-07 at 9 57 54 AM" src="https://user-images.githubusercontent.com/3190176/206259796-1d6550fe-ee09-43ec-bd98-77b6d0c5b0d3.png">

**Comment by bryantbiggs** [comment]
I don't see those errors on my end - it looks like TFC/TFE is evaluating the policy, or attempting to, and stating that the entity creating the key won't be able to manage it in the future.

by default, the module will add the identity who creates the cluster resources into the key policy as an admin https://github.com/terraform-aws-modules/terraform-aws-eks/blob/7124d7603a81ad07bbcc7a932ba0f41989365471/main.tf#L125

however, users can update to suit their needs. for example, you can enable the default KMS key policy which gives access to all users of the account by setting  `enable_default_policy = true` or you scope the policy based on different roles and the type of access they need to the key

**Comment by pdeva** [comment]
>  it looks like TFC/TFE is evaluating the policy

actually this error message is from the aws provider. tfc does not know anything special about aws, it just executes terraform. it seems the fact that the identity being used is a role and not a user might be causing the issue.

**Comment by pdeva** [comment]
so the key part i believe is this (pasting snippet from code snippet in my top post):

```hcl
provider "aws" {
  assume_role {
    role_arn = "arn:aws:iam::172512501118:role/terraform"
  }
}
```

the aws provider is using a 'role' instead of a 'user' which might be the issue.

**Comment by erltho** [comment]
is this one really closed? 
@pdeva were you able to provision when assuming a role?

**Comment by pdeva** [comment]
it does not work when you assume a role. the bug is actually open and can be easily reproduced if you use the code sample in original post, including the `aws.assume_role` block.

**Comment by erltho** [comment]
Yes thank you, I can confirm we have problems as well. 

@bryantbiggs Can you reopen this issue?

**Comment by bryantbiggs** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/28381

**Comment by bryantbiggs** [comment]
for now, to get around this you can set the `kms_key_administrators` directly. Using @pdeva's example:

```hcl
provider "aws" {
  region              = "us-east-1"
  allowed_account_ids = ["172512501118"]
  assume_role {
    role_arn = "arn:aws:iam::172512501118:role/terraform"
  }
}

module "eks_cluster" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "~> 19.0"
  vpc_id          = module.vpc.vpc_id
  cluster_name    = "k1"
  cluster_version = "1.24"
  subnet_ids      = module.vpc.private_subnet_ids
 
  # Add this line to match the assumed role ARN
  kms_key_administrators = ["arn:aws:iam::172512501118:role/terraform"]

  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = false
}
```

**Comment by fknittel** [comment]
@bryantbiggs I would instead suggest the following generic work-around, which uses [aws_iam_session_context](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_session_context) to resolve the issue and might also be the approach terraform-aws-eks should use internally:

```terraform
provider "aws" {
  region              = "us-east-1"
  allowed_account_ids = ["172512501118"]
  assume_role {
    role_arn = "arn:aws:iam::172512501118:role/terraform"
  }
}
data "aws_caller_identity" "current" {}
data "aws_iam_session_context" "current" {
  # "This data source provides information on the IAM source role of an STS assumed role. For non-role ARNs, this data source simply passes the ARN through in issuer_arn."
  arn = data.aws_caller_identity.current.arn
}
module "eks_cluster" {
  source          = "terraform-aws-modules/eks/aws"
  version         = "~> 19.0"
  vpc_id          = module.vpc.vpc_id
  cluster_name    = "k1"
  cluster_version = "1.24"
  subnet_ids      = module.vpc.private_subnet_ids

  kms_key_administrators = [data.aws_iam_session_context.current.issuer_arn]

  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = false
}
```

**Comment by bryantbiggs** [comment]
ooh, I did not know about this data source. let me give it a try - thank you

**Comment by bryantbiggs** [comment]
oh that works beautifully - thank you @fknittel

**Comment by msf-woven** [comment]
In complex CI setups that use assume-role heavily using the above approach produces a policy change on every apply. 

```
  # module.kms.aws_kms_key.this[0] will be updated in-place
  ~ resource "aws_kms_key" "this" {
        id                                 = "8dfc8cae-49d5-4377-81bf-753506d3215b"
      ~ policy                             = jsonencode(
          ~ {
              ~ Statement = [
                    {
                        Action    = "kms:*"
                        Effect    = "Allow"
                        Principal = {
                            AWS = "arn:aws:iam::303349233740:root"
                        }
                        Resource  = "*"
                        Sid       = "Default"
                    },
                  ~ {
                      ~ Principal = {
                          ~ AWS = "arn:aws:sts::303349233740:assumed-role/DelegatedAdminRole/aws-go-sdk-1671752848055475303" -> "arn:aws:sts::303349233740:assumed-role/DelegatedAdminRole/aws-go-sdk-1671753029714925323"
                        }
                        # (4 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        tags                               = {}
        # (10 unchanged attributes hidden)
    }
```
