### ISSUE TITLE
Bug/Breaking change introduced in v20.8.3

### ISSUE THREAD

**Issue by andremachado94** [terraform-aws-modules/terraform-aws-eks#2970]
## Description

Have a series of CICD pipelines that started failing when patch version [20.8.3](https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v20.8.3) was released. Seems to be a breaking change from the previous one originating from [PR-2963](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2963)

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version: 20.8.3

- Terraform version: 1.6.6

- Provider version(s):
  - registry.terraform.io/hashicorp/aws: 5.40.0
  - registry.terraform.io/hashicorp/kubernetes: 2.27.0

## Reproduction Code 

Can't provide a minimal reproducible example at the moment. Will try to do it soon.

## Expected behavior

Successful plan step.

## Actual behavior

Plan step fails with the following error:

```
│ Error: Resource precondition failed
│ 
│   on .terraform/modules/cluster.eks_managed_node_group/modules/_user_data/main.tf line 10, in resource "null_resource" "validate_cluster_service_cidr":
│   10:       condition     = var.create ? length(local.cluster_service_cidr) > 6 : true
│     ├────────────────
│     │ local.cluster_service_cidr is ""
│     │ var.create is true
│ 
│ `cluster_service_cidr` is required when `create = true`.
╵
```

## Additional context

None for now.

**Comment by bryantbiggs** [comment]
that is not a breaking change - thats simply expanding the scope of functionality of the module and ensuring failure to do so is not silent 

I am going to assume you are using a node group that is defined on its own (separate module instantiation) as opposed to creating nodegroups through the root module, is that correct?

**Comment by andremachado94** [comment]
Hi @bryantbiggs yes, that is correct. Shouldn't the validation then be on the root module to allow this use-case?

**Comment by bryantbiggs** [comment]
again, to be fair - nothing is breaking. we have fixed a bug, and in order to fix said bug, a value is required. when users create nodegroups through the root module (i.e. - like [this](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/1627231af669796669ce83e0a4672a7e6d94a0b3/examples/eks_managed_node_group/main.tf#L73)), there is no change required on their end. The module itself ensures the required values are passed down to the sub-modules [correctly](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/1627231af669796669ce83e0a4672a7e6d94a0b3/node_groups.tf#L38). 

Its only in the scenario where  users have "disconnected" nodegroups, those that are defined outside of the root module like [this](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/1627231af669796669ce83e0a4672a7e6d94a0b3/examples/eks_managed_node_group/main.tf#L357), where we need to ensure that users provide this key piece of information in order to avoid the prior bug. In addition, on AL2 AMIs, the service CIDR has always been option, but with the change to AL2023, the service team is requiring this input. So we are aligning with that expectation here

**Comment by andremachado94** [comment]
Ok, didn't understood that was a required input for AL2023. We can easily fix this on our side, however I'm still not very convinced this should be a patch version upgrade 😄 

Either way, thanks for the fast response! I'll close this issue

**Comment by clevandowski** [comment]
Thanks for your help @bryantbiggs
