### ISSUE TITLE
Cannot disable instance_refresh in self-managed-node-group since v21.x

### ISSUE THREAD

**Issue by jcabillot** [terraform-aws-modules/terraform-aws-eks#3460]
## Description

Since the upgrade to module version 21.x, the instance_refresh variable in the self-managed-node-group submodule is now defined with nullable = false : https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/self-managed-node-group/variables.tf#L727

Previously, it was possible to disable instance_refresh by setting it to null and the logic is still here: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v21.0.6/modules/self-managed-node-group/main.tf#L529
Now by defining it to null, it gets the default value from : https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/self-managed-node-group/variables.tf#L721

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version 21.x:

- Terraform version: 1.12.1
- Provider version(s): aws 6.6.0

**Comment by abaidgulshan** [comment]
any update on this?

**Comment by antonbabenko** [comment]
This issue has been resolved in version 21.0.8 :tada:

**Comment by resuzuke** [comment]
I don't think this issue is solved. Setting `instance_refresh = null` still resolves to
```
      + instance_refresh {
          + strategy = "Rolling"
        }
```

**Comment by gleidsoncampos** [comment]
confirmed, still happening.

**Comment by jcabillot** [comment]
@bryantbiggs @antonbabenko the issue is still present : 

With `instance_refresh = null`

```
  # module.aws-foundation.module.eks.module.self_managed_node_group["general-purpose-0"].aws_autoscaling_group.this[0] will be updated in-place
  ~ resource "aws_autoscaling_group" "this" {
        id                               = "prod-eks-gp-0-20240918142830380900000020"
        name                             = "prod-eks-gp-0-20240918142830380900000020"
        # (32 unchanged attributes hidden)

      + instance_refresh {
          + strategy = "Rolling"

          + preferences {
              + max_healthy_percentage       = 100
              + min_healthy_percentage       = 66
              + scale_in_protected_instances = "Ignore"
              + skip_matching                = false
              + standby_instances            = "Ignore"
            }
        }

      ~ mixed_instances_policy {
          ~ launch_template {
              ~ launch_template_specification {
                  ~ version              = "29" -> (known after apply)
                    # (2 unchanged attributes hidden)
                }

                # (5 unchanged blocks hidden)
            }

            # (1 unchanged block hidden)
        }

      - timeouts {}

        # (15 unchanged blocks hidden)
    }
```

With `instance_refresh = {}`
```
  ~ resource "aws_autoscaling_group" "this" {
        id                               = "prod-eks-gp-0-20240918142830380900000020"
        name                             = "prod-eks-gp-0-20240918142830380900000020"
        # (32 unchanged attributes hidden)

      + instance_refresh {
          + strategy = "Rolling"
        }

      ~ mixed_instances_policy {
          ~ launch_template {
              ~ launch_template_specification {
                  ~ version              = "29" -> (known after apply)
                    # (2 unchanged attributes hidden)
                }

                # (5 unchanged blocks hidden)
            }

            # (1 unchanged block hidden)
        }

      - timeouts {}

        # (15 unchanged blocks hidden)
    }
```

**Comment by antonbabenko** [comment]
This issue has been resolved in version 21.0.9 :tada:

**Comment by jcabillot** [comment]
@bryantbiggs @antonbabenko thanks a lot, that change fixed my issue :  

With `instance_refresh = {}`:  
```
  ~ resource "aws_autoscaling_group" "this" {
        id                               = "prod-eks-gp-0-20240918142830380900000020"
        name                             = "prod-eks-gp-0-20240918142830380900000020"
        # (32 unchanged attributes hidden)

      ~ mixed_instances_policy {
          ~ launch_template {
              ~ launch_template_specification {
                  ~ version              = "29" -> (known after apply)
                    # (2 unchanged attributes hidden)
                }

                # (5 unchanged blocks hidden)
            }

            # (1 unchanged block hidden)
        }

      - timeouts {}

        # (15 unchanged blocks hidden)
    }
```
