### ISSUE TITLE
Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by vranystepan** [terraform-aws-modules/terraform-aws-eks#481]
# I have issues
I can't create an EKS cluster as it's failing on ` module.<redacted>.aws_autoscaling_group.workers[0]`

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [x] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
when applying following configuration

```hcl
resource "aws_security_group" "all_worker_http_https" {
  name_prefix = "all_worker_http_https"
  vpc_id      = data.terraform_remote_state.vpc.outputs.vpc_id

  ingress {
    from_port = 80
    to_port   = 80
    protocol  = "tcp"

    cidr_blocks = [
      "0.0.0.0/0",
    ]
  }

  ingress {
    from_port = 443
    to_port   = 443
    protocol  = "tcp"

    cidr_blocks = [
      "0.0.0.0/0",
    ]
  }
}

locals {
  worker_groups = [
    {
      instance_type        = var.instance_type
      name                 = var.worker_name
      asg_max_size         = 6
      asg_desired_capacity = 3
      asg_min_size         = 3
      autoscaling_enabled  = true

      # additional_userdata  = "echo foo bar"
    },
  ]

  tags = {
    environment = var.environment
    githubrepo  = var.githubrepo
  }
}

module "<redacted>" {
  source                                       = "../../modules/terraform-aws-eks/"
  cluster_name                                 = var.cluster_name
  subnets                                      = data.terraform_remote_state.vpc.outputs.private_subnets
  vpc_id                                       = data.terraform_remote_state.vpc.outputs.vpc_id
  cluster_enabled_log_types                    = var.cluster_enabled_log_types
  worker_groups                                = local.worker_groups
  worker_additional_security_group_ids         = [aws_security_group.all_worker_http_https.id]
  workers_additional_policies                  = [aws_iam_policy.ingress_policy.arn, aws_iam_policy.cluster_autoscaler_policy.arn]
  map_roles                                    = var.map_roles
  map_accounts                                 = var.map_accounts
  tags                                         = local.tags
  cluster_version                              = var.cluster_version
  kubeconfig_aws_authenticator_additional_args = var.kubeconfig_aws_authenticator_additional_args
  kubeconfig_aws_authenticator_env_variables   = var.kubeconfig_aws_authenticator_env_variables
}

```

we're getting 

```
-----------------------------------------------------
2019/08/26 05:15:22 [DEBUG] [aws-sdk-go] {}

Error: Provider produced inconsistent final plan

When expanding the plan for module.<redacted>.aws_autoscaling_group.workers[0]
to include new values learned so far during apply, provider "aws" produced an
invalid new value for .initial_lifecycle_hook: planned set element
cty.ObjectVal(map[string]cty.Value{"default_result":cty.UnknownVal(cty.String),
"heartbeat_timeout":cty.UnknownVal(cty.Number),
"lifecycle_transition":cty.UnknownVal(cty.String),
"name":cty.UnknownVal(cty.String),
"notification_metadata":cty.UnknownVal(cty.String),
"notification_target_arn":cty.UnknownVal(cty.String),
"role_arn":cty.UnknownVal(cty.String)}) does not correlate with any element in
actual.
```

We suspect that [dynamic blocks](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers.tf#L77-L88) are misbehaving since we can see `initial_lifecycle_hook` blocks in the plan. 

```
# module.<redacter>aws_autoscaling_group.workers[0] will be created
  + resource "aws_autoscaling_group" "workers" {
      + arn                       = (known after apply)
      + availability_zones        = (known after apply)
      + default_cooldown          = (known after apply)
      + desired_capacity          = 3
      + enabled_metrics           = (known after apply)
      + force_delete              = (known after apply)
      + health_check_grace_period = 300
      + health_check_type         = (known after apply)
      + id                        = (known after apply)
      + launch_configuration      = (known after apply)
      + load_balancers            = (known after apply)
      + max_size                  = 6
      + metrics_granularity       = "1Minute"
      + min_size                  = 3
      + name                      = (known after apply)
      + name_prefix               = (known after apply)
      + placement_group           = (known after apply)
      + protect_from_scale_in     = (known after apply)
      + service_linked_role_arn   = (known after apply)
      + suspended_processes       = (known after apply)
      + tags                      = (known after apply)
      + target_group_arns         = (known after apply)
      + termination_policies      = (known after apply)
      + vpc_zone_identifier       = (known after apply)
      + wait_for_capacity_timeout = "10m"

      + initial_lifecycle_hook {
          + default_result          = (known after apply)
          + heartbeat_timeout       = (known after apply)
          + lifecycle_transition    = (known after apply)
          + name                    = (known after apply)
          + notification_metadata   = (known after apply)
          + notification_target_arn = (known after apply)
          + role_arn                = (known after apply)
        }
    }
```

We suppose they should be not there as `worker_group` does not have `asg_initial_lifecycle_hooks` specified and `local.workers_group_defaults["asg_initial_lifecycle_hooks"]` = `[]`

## Environment details

* Affected module version: `d6d0975`
* OS: any
* Terraform version: 0.12.7

**Comment by dpiddockcmp** [comment]
Hi @vranystepan ,

This is one of those tricky Terraform edge cases to do with how it handles locals and variables with resources.

The issue: if a variable or local contains an unknown value then the whole variable/local is tagged as unknown in the diff state. Fine for simple variables but really annoying when dealing with collections. This makes terraform do weird things in dynamic blocks. It assumes it can't use anything from the collection until apply time. When it turns out that the referred to list is in fact empty and.. oops.

Potential solutions for you (and anyone else playing along on master):
- revert #466 in your local copy of the module.
- Do targeted applies of resources referenced by `local.workers_group_defaults` within the module. Data sources should be fine:
  - `module.<redacted>.aws_iam_role.workers`
  - your subnets being passed in as `var.subnets`
  - anything you reference in `var.worker_groups` and `var.workers_group_defaults`
- set something so that `initial_lifecycle_hooks` is valid.

I think that #466 needs reworking. I don't know if the independent `autoscaling_lifecycle_hooks` resource could be used instead?

**Comment by vranystepan** [comment]
@dpiddockcmp  thanks for explanation, makes sense. We've disabled `autoscaling_lifecycle_hooks` in our local copy as we don't use them. But that is not desired solution ... In the mean time we'll most likely use v5.1.0 as this version does not have `autoscaling_lifecycle_hooks`

Thanks again for your prompt reaction.

**Comment by barryib** [comment]
@vranystepan I'm trying unsuccessfully to reproduce this. Can you please share your configuration ? I tried with with existing and full new deployments.

@dpiddockcmp Thanks for your explanation. It's sound like there are few opened issue on terraform dynamic blocks with "not yet know" values. But after the first apply, I'm not getting `initial_lifecycle_hook` block in my plan anymore.

> set something so that initial_lifecycle_hooks is valid

What do you mean by that ?

> I think that #466 needs reworking. I don't know if the independent autoscaling_lifecycle_hooks resource could be used instead?

Some answers https://github.com/terraform-aws-modules/terraform-aws-eks/pull/466#issuecomment-519139165

**Comment by dpiddockcmp** [comment]
> @vranystepan I'm trying unsuccessfully to reproduce this. Can you please share your configuration ? I tried with with existing and full new deployments.

It's easier to reproduce if you strip right back to the core issue. Try these:
`root.tf`:
```hcl
provider "aws" {}

variable "az" {}

data "aws_ami" "this" {
  filter {
    name   = "name"
    values = ["amzn-ami-hvm-*-x86_64-gp2"]
  }
  most_recent = true
  owners      = ["amazon"]
}

resource "aws_instance" "this" {
  instance_type = "t2.micro"
  ami           = data.aws_ami.this.id
}

module "asg" {
  source = "./module"
  ami    = data.aws_ami.this.id
  az     = var.az
  input = {
    instance                    = aws_instance.this.id
    asg_initial_lifecycle_hooks = []
  }
}
```
`module/main.tf`:
```
variable "ami" {}
variable "az" {}
variable "input" {}

resource "aws_launch_configuration" "this" {
  name_prefix   = "test"
  image_id      = var.ami
  instance_type = "t2.micro"
}

resource "aws_autoscaling_group" "this" {
  availability_zones   = [var.az]
  min_size             = 0
  max_size             = 0
  launch_configuration = aws_launch_configuration.this.name
  dynamic "initial_lifecycle_hook" {
    for_each = lookup(var.input, "asg_initial_lifecycle_hooks", [])
    content {
      name                 = lookup(initial_lifecycle_hook.value, "name", null)
      lifecycle_transition = lookup(initial_lifecycle_hook.value, "lifecycle_transition", null)
    }
  }
}
```
Terraform will create the launch_configuration and instance (assuming your region still has the default VPC) and then fail with the error `Provider produced inconsistent final plan`. It will succeed on a second apply.

> @dpiddockcmp Thanks for your explanation. It's sound like there are few opened issue on terraform dynamic blocks with "not yet know" values. But after the first apply, I'm not getting `initial_lifecycle_hook` block in my plan anymore.

They will go away once Terraform can resolve all the references. You have to test on an empty state.

> > set something so that initial_lifecycle_hooks is valid
> 
> What do you mean by that ?

Terraform needs something inside `initial_lifecycle_hooks` for the first plan to be consistent. So for my example above the following is enough for the plan to apply cleanly first time but wouldn't be a very good user experience:
```
asg_initial_lifecycle_hooks = [{
  name                 = "test"
  lifecycle_transition = "autoscaling:EC2_INSTANCE_LAUNCHING"
}]
```

**Comment by barryib** [comment]
@dpiddockcmp thanks for the configuration files. I was able to reproduce it. I didn't get into this issue because I did my tests (with and without lifecycle hooks) on the same states => so I didn't get into the "know after apply" issue.

I was able to fix this, by defining a new variable `worker_create_initial_lifecycle_hooks` which is `false` by default. When set to `true`, the module will try to create life cycle hooks. That's mean, correct ones should be provided.

We'll get something like this:

```hcl
resource "aws_autoscaling_group" "this" {
  availability_zones   = [var.az]
  min_size             = 0
  max_size             = 0
  launch_configuration = aws_launch_configuration.this.name
  dynamic "initial_lifecycle_hook" {
    for_each = var.worker_create_initial_lifecycle_hooks ? lookup(var.input, "asg_initial_lifecycle_hooks", []) : []
    content {
      name                 = lookup(initial_lifecycle_hook.value, "name", null)
      lifecycle_transition = lookup(initial_lifecycle_hook.value, "lifecycle_transition", null)
    }
  }
}
```

For the recored, I opened an issue in terraform-provider-aws https://github.com/terraform-providers/terraform-provider-aws/issues/9882

@dpiddockcmp @max-rocket-internet any thoughts ?

**Comment by vranystepan** [comment]
Wow, that was quick. Thank you all! ❤️

**Comment by barryib** [comment]
Another strange behavior or terraform, is by using `length` function and conditional evaluation in the `for_each` we can get ride from the "known after apply" issue.

@dpiddockcmp so life cycle hooks dynamic blocks becomes

```hcl
dynamic "initial_lifecycle_hook" {
    for_each = length(lookup(var.input, "asg_initial_lifecycle_hooks", [])) > 0 ? lookup(var.input, "asg_initial_lifecycle_hooks", []) : []
    content {
      name                 = lookup(initial_lifecycle_hook.value, "name", null)
      lifecycle_transition = lookup(initial_lifecycle_hook.value, "lifecycle_transition", null)
    }
}
```
@vranystepan can you check if https://github.com/terraform-aws-modules/terraform-aws-eks/pull/483 fix your issue ?

**Comment by dpiddockcmp** [comment]
That's really interesting behaviour. I didn't expect that to work but it does on the small test case 😄

**Comment by apolegoshko** [comment]
+1 for this. If I ran `terraform apply` right after failed execution, everything looks good.

**Comment by barryib** [comment]
@dpiddockcmp @max-rocket-internet @vranystepan It sounds like it's fixed in [Terraform 0.12.8 ](https://github.com/hashicorp/terraform/blob/v0.12.8/CHANGELOG.md) with https://github.com/hashicorp/terraform/pull/22597. Terraform now handle correctly unknown values in for_each.

**Comment by apolegoshko** [comment]
I've rolled back to eks modules which is tagged by 5.0.0 and everything works as expected.

**Comment by apolegoshko** [comment]
@barryib  @dpiddockcmp @max-rocket-internet @vranystepan just checked with latest `terraform 0.12.8` (+ terraform-eks modules latest (from master branch)) and it still doesn't work:

```bash
Error: Provider produced inconsistent final plan

When expanding the plan for module.my-cluster.aws_autoscaling_group.workers[0]
to include new values learned so far during apply, provider "aws" produced an
invalid new value for .initial_lifecycle_hook: planned set element
cty.ObjectVal(map[string]cty.Value{"default_result":cty.UnknownVal(cty.String),
"heartbeat_timeout":cty.UnknownVal(cty.Number),
"lifecycle_transition":cty.UnknownVal(cty.String),
"name":cty.UnknownVal(cty.String),
"notification_metadata":cty.UnknownVal(cty.String),
"notification_target_arn":cty.UnknownVal(cty.String),
"role_arn":cty.UnknownVal(cty.String)}) does not correlate with any element in
actual.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

While the next `terraform apply` command applies without any other error.

**Comment by barryib** [comment]
@apolegoshko thanks for your feedback. Is this PR https://github.com/terraform-aws-modules/terraform-aws-eks/pull/489 solve the problem ?

**Comment by apolegoshko** [comment]
Hey @barryib 

Glad to inform you that PR #489 solves issue for me. I'm using module near as is stored in `master` branch (except that I providing info about vpc and subnets).
